"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g8!j&$kg%c8(wx$2@enq@sk+jzkz38%x11y8p4wcild1-1y2+%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders', 
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',  
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'astrogyan',
        'USER':'root',
        'PASSWORD': 'password2025',
        'HOST': 'localhost',
        'PORT': '3306',

    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Ephemeris path for Swiss Ephemeris
EPHE_PATH = BASE_DIR / 'ephemeris'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # ── Rate limiting ──────────────────────────────────────────────────────────
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon':              '100/hour',    # unauthenticated — 100 req/hour
        'user':              '1000/hour',   # authenticated  — 1000 req/hour
        'chart':             '30/minute',   # heavy endpoints (chart, antardasha)
        'compatibility':     '20/minute',   # compatibility endpoints
        'transits':          '60/minute',   # transit endpoints
    },

}

# ─── CORS ──────────────────────────────────────────────────────────────────────
# Development — allow all origins
CORS_ALLOW_ALL_ORIGINS = True   # Set False in production


# Production — whitelist specific origins like:
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     "https://yourfrontend.com",
#     "https://app.astrogyan.com",
#     "http://localhost:3000",
# ]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE'
    'OPTIONS',
]


CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'x-requested-with',
    'x-api-key',           # for future API key auth
]

CORS_ALLOW_CREDENTIALS = False         # Set True if you add cookie-based auth
CORS_PREFLIGHT_MAX_AGE = 86400         # Cache preflight for 24 hours


# ─── Security Headers (Helmet equivalent) ─────────────────────────────────────
# Django's built-in SecurityMiddleware settings
SECURE_BROWSER_XSS_FILTER       = True
SECURE_CONTENT_TYPE_NOSNIFF     = True
X_FRAME_OPTIONS                 = 'DENY'


# Enable these in production (requires HTTPS):
# SECURE_SSL_REDIRECT             = True
# SECURE_HSTS_SECONDS             = 31536000   # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
# SECURE_HSTS_PRELOAD             = True
# SESSION_COOKIE_SECURE           = True
# CSRF_COOKIE_SECURE              = True


# ─── Content Security Policy (django-csp) ─────────────────────────────────────
CSP_DEFAULT_SRC  = ("'self'",)
CSP_SCRIPT_SRC   = ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net")   # for Swagger UI
CSP_STYLE_SRC    = ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net")
CSP_IMG_SRC      = ("'self'", "data:", "cdn.jsdelivr.net")
CSP_FONT_SRC     = ("'self'", "cdn.jsdelivr.net")
CSP_CONNECT_SRC  = ("'self'",)
CSP_FRAME_SRC    = ("'none'",)
CSP_OBJECT_SRC   = ("'none'",)
CSP_BASE_URI     = ("'self'",)
CSP_FORM_ACTION  = ("'self'",)



# Swagger / OpenAPI docs configuration
# ─── Spectacular ───────────────────────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE':       'AstroGyan API',
    'DESCRIPTION': 'Open-source Vedic Astrology (Jyotish) REST API — Lahiri ayanamsa, Swiss Ephemeris',
    'VERSION':     '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'TAGS': [
        {'name': 'Chart',         'description': 'Birth chart — planets, ascendant, houses'},
        {'name': 'Panchang',      'description': 'Nakshatra, Tithi, Vara, Yoga, Karana'},
        {'name': 'Dasha',         'description': 'Vimshottari Mahadasha & Antardasha'},
        {'name': 'Divisional',    'description': 'D-series charts (D2–D60)'},
        {'name': 'Yogas',         'description': 'Vedic yoga detection'},
        {'name': 'Ashtakavarga',  'description': 'Planetary strength scoring'},
        {'name': 'Compatibility', 'description': 'Kundali Milan — Guna matching & Mangal Dosha'},
        {'name': 'Transits',      'description': 'Gochar — current & date-specific transits'},
    ],
}


# ─── Static / i18n ────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True
STATIC_URL    = 'static/'